baseURL = "https://optimistic-borg-891d8a.netlify.app/"
homeURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"

[languages]
    [languages.en]
        LanguageName = "English"
        weight = 1
    [languages.cs]
        LanguageName = "Česky"
        weight = 2